services:
  mcp-paperless-ngx:
    build: .
    image: mcp-paperless-ngx
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      MCP_TRANSPORT: "streamable-http"
      MCP_HOST: "0.0.0.0"
      MCP_PORT: "8001"
